kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    pull: never
    image: infinitime-build
    volumes:
      - name: sources
        path: /sources
      - name: dockersock
        path: /var/run
    commands:
      - sleep 10 # give docker enough time to start
      - /opt/build.sh pinetime-app

services:
  - name: docker
    image: infinitime-build
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: sources
    host:
      path: /drone/src